### ISSUE TITLE
Add extra stamps

### ISSUE THREAD

**Issue by nedrichards** [flathub/org.tuxpaint.Tuxpaint#1]
Tux Paint has a number of [optional 'stamps' available](http://www.tuxpaint.org/download/source/) for use. It'd be great if we could get these into an extension (or ship in the main download) as they're a lot of the joy of the application for younger users.

**Comment by cosimoc** [comment]
I created https://github.com/flathub/org.tuxpaint.Tuxpaint/pull/2 that should fix it -- any chance you could test that?

**Comment by nedrichards** [comment]
Sure

**Comment by nedrichards** [comment]
![screenshot from 2017-08-16 23-11-33](https://user-images.githubusercontent.com/302677/29387577-8242dc9c-82d8-11e7-9f17-174834644cc1.png)

**Comment by cosimoc** [comment]
Merged!
