### ISSUE TITLE
Update to 0.9.25

### ISSUE THREAD

**Issue by billkendrick** [flathub/org.tuxpaint.Tuxpaint#11]
We recently released Tux Paint 0.9.25. The changes were mostly minor, but it now supports exporting drawings to one's ~/Pictures folder (technically, it's wherever $XDG_PICTURES_DIR points, with $HOME/Pictures as a fallback), as well as exporting slideshows as animated GIFs (which adds a dependency on the "libimagequant" library, which is part of "pngquant2").

Press release: http://www.tuxpaint.org/latest/tuxpaint-0.9.25-press-release-en.php

Thanks for your consideration & happy new year!

**Comment by wjt** [comment]
Thanks for the ping, and the details of the new dependency and interaction with the system! I've wired this package up to release-monitoring.org so PRs will automatically appear on future releases. :-)

**Comment by billkendrick** [comment]
Thanks! I've noted the update over on the official website.

**Comment by billkendrick** [comment]
Thanks again. We've had a request over on Twitter for a 32-bit Flatpak build of Tux Paint 0.9.25, as well. Would that be possible?

**Comment by wjt** [comment]
Sorry, not really. None of the supported runtimes are built for 32-bit architectures, only x86_64 and aarch64.
