### ISSUE TITLE
Switch to SDL 2

### ISSUE THREAD

**Issue by wjt** [flathub/org.tuxpaint.Tuxpaint#21]
This build currently uses mainline releases of TuxPaint, which use SDL 1.2. There is an actively-maintained sdl2 branch upstream https://sourceforge.net/p/tuxpaint/tuxpaint/ci/sdl2.0/tree/ which I believe is used to build the Android version of the app. One nice thing that SDL 2 would bring is (at some point) Wayland support.

**Comment by wjt** [comment]
@billkendrick Is there a plan to make the SDL2 branch the mainline? Does it have feature parity with the mainline branch?

**Comment by billkendrick** [comment]
Seriously considering it. I've added a lot of new features to the upcoming version, so would prefer not to throw "total library upgrade" into it. I'm thinking the subsequent version could be (basically) nothing but an SDL1.2->2.0 transition, with no major new features. (That way, if anything fails, users can at least revert to the previous, SDL1.2-based version.)

My main concern was losing some older platforms, but SDL2.0 supports Windows as far back as XP, and macOS further back (10.5) than Tux Paint currently supports (10.10). Ref: https://twitter.com/icculus/status/1442902492572909568

**Comment by billkendrick** [comment]
Announced it to the TP team https://sourceforge.net/p/tuxpaint/mailman/message/37357884/

**Comment by wjt** [comment]
I'm working on the 0.9.29 update on #27. Seems to work well on Wayland in my quick testing!
