### ISSUE TITLE
Both x11 and fallback-x11 usage will be blocked via linter

### ISSUE THREAD

**Issue by bbhtt** [flathub/org.tuxpaint.Tuxpaint#56]
See the note here https://docs.flatpak.org/en/latest/sandbox-permissions.html#standard-permissions

**Comment by wjt** [comment]
Listing both is harmless on Flatpak 0.11.3 and newer, which understand `fallback-x11` and ignore `x11` if both are present.

On Flatpak 0.11.2 and older, `fallback-x11` is not understood and is ignored, so `x11` is used and the application will continue to work on an X11 session.

I appreciate that 0.11.3 was released in February 2018 and that https://ahayzen.com/direct/flathub.html#downloadsbyflatpakstacked implies that there are no remaining users of Flatpak ≤ 0.11.2 so it is now unnecessary to use both; and that writing this comment has taken me longer than just removing one line of the manifest would; but it's busywork…

**Comment by bbhtt** [comment]
The goal is to prevent new submissions from adding this by mistake, because in 99% of the time, new submissions add both thinking something else and then things don't work.

**Comment by wjt** [comment]
OK, fair enough! Thank you for the explanation of why it's worth doing.
